server:
  port: ${SS_SERVER_PORT:7879}

spring:
  profiles:
    active: utils, security-utils
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

zuul:
  host:
    max-per-route-connections: 1000
    socket-timeout-millis: 180000
    connect-timeout-millis: 60000
  routes:
    stock:
      path: /yanbin/stock/**
      url: ${STOCK_BASE_URL:http://192.168.1.10:1700}
      strip-prefix: false